spring.application.name=ProgInz_Seminars2_2026

#konfiguracija ar MySQL
spring.jpa.hibernate.ddl-auto=create-drop
spring.datasource.url=jdbc:mysql://${MYSQL_HOST:localhost}:3306/miniunips2
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name =com.mysql.jdbc.Driver